### ISSUE TITLE
[BE] 댓글 api 수정 요청

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#195]
### 1. feelings 데이터 관련해서 팀이랑 유저가 양식이 다릅니다. 

둘중 어느 데이터 타입이 맞을까요? 

이전에 정해준 api명세

```
"feeling":[ //좋아요한 사람들 id
  "user_id" : "int",
  "user_id2" : "int",
...
]
```

`GET /api/user/comment/{user_id}` 
```
  "feelings": [
        {
          "id": 0,
          "userId": 0
        }
      ],
```

`GET /api/team/comment/{team_id}`

```
  "feelings": [
    0
  ],
```

### 2. 유저 이미지데이터 관련한 key값이 없습니다.  

추가부탁드립니다.

```
  "data": [
    {
      "comments": [
        null
      ],
      "content": "string",
      "feelings": [
        {
          "id": 0,
          "userId": 0
        }
      ],
      "parentId": 0,
      "secret": true,
      "userId": 0,
      "writer": "string"
    }
  ],
```

### 3. 대댓글 관련해서 Example value가 swagger에 나와있지 않습니다. 

추가 부탁드립니다. 

### 4. 대댓글 key값 네이밍

이전에는 대댓글 key값을 replies로 정했었는데 comments로 바꾼 이유가 있을까요? 댓글과 대댓글 구분하기 위해서 replies가 더 좋아보입니다.  

이전에 정해준 api명세

```
"replies": [], // 대댓글
```

### 5. 작성자정보와 게시글 주인 정보 

로그인한 유저: A (이왜진)
유저 게시글 주인: B (왕)

댓글을 작성후 다시 요청하면 writer정보로 작성자가 아닌 유저 게시글 주인 정보가 들어 있습니다. 

```댓글 작성시 제출하는 정보들```

<img width="401" alt="스크린샷 2022-09-27 오후 11 11 34" src="https://user-images.githubusercontent.com/71386219/192550139-9b24b1c0-1a29-447c-bae9-b69b3281c9f1.png">

```댓글 목록 요청```
<img width="395" alt="스크린샷 2022-09-27 오후 11 12 18" src="https://user-images.githubusercontent.com/71386219/192550329-a4eb79c3-97b4-4ad6-9419-2f9b0db956ad.png">

### 6. 댓글 GET요청의 응답값으로 댓글 고유의 id가 포함되어 있지 않습니다.

추가바랍니다. 

```
  {
          "writer": "왕",
          "userId": 1045064556,
          "secret": false,
          "content": "asdf",
          "comments": [],
          "feelings": []
},
```

**Comment by philos1234** [comment]
2번 내용이 무슨 말인지 잘 모르겠습니다.
