### ISSUE TITLE
[BE] (유저) 댓글 삭제, 수정, 생성 API 수정 요청

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#207]
[1. Swagger 상에서 parameter 수정 요청]()
[2. 댓글 관련해서 db조회 결과와 swagger 요청 결과가 다릅니다. ]()
[3. 댓글 조회 생성 시간 관련 데이터 추가 요청]()

## 1. Swagger 상에서 parameter 수정 요청

swagger에서 아래 두 개의 API요청을 할 때 request값이 `userCommentReqDto`전체가보입니다. 필요한 데이터만 요청할 수 있도록 수정해야합니다.  팀 댓글과 유저 대댓글, 팀 대댓글 관련해서도 확인 부탁드립니다~

- `POST /api/user/comment`: 유저 댓글 달기, 
- `PACTH /api/user/comment`: 유저 게시글 댓글 수정 

현재

<img width="456" alt="스크린샷 2022-10-09 오후 9 25 56" src="https://user-images.githubusercontent.com/71386219/194756713-ee2a2468-8722-4501-8a6c-8db5ed6b4519.png">

수정 예시

```json
{
	"userId" : "Long", //댓글이 속한 유저 게시물 id
        "userName" : "String" //댓글 작성자
	"parentId" : "Long" //반드시 부모 댓글 id넣어야 대댓글이됨
	"secret" : "boolean",
	"content" : "String"
}
```

## 2. 댓글 관련해서 db조회 결과와 swagger 요청 결과가 다릅니다. 

댓글 id관련해서 db조회결과와 swagger 요청 결과가 다릅니다. 이것 때문에 `DELETE /api/comment/{comment_id}: 유저 게시글 (대)댓글 삭제` 요청시 id값을 찾는 못하는 것 같은데 확인 부탁드려요.

db조회 결과
<img width="647" alt="스크린샷 2022-10-09 오후 9 32 51" src="https://user-images.githubusercontent.com/71386219/194757026-848292d7-06d2-410f-9df4-8c7f87a8f73b.png">

swagger조회결과

```json
{
    "status": "OK",
    "code": 1000,
    "message": "요청 성공",
    "data": [
        {
            "userInfo": {
                "id": 9021279491,
                "name": "이왜진123",
                "image": ""
            },
            "id": 6888271142, // 댓글 id
            "secret": false,
            "content": "123",
            "replies": [],
            "feelings": []
        },
        {
            "userInfo": {
                "id": 9021279491,
                "name": "이왜진123",
                "image": ""
            },
            "id": 4829645132, // 댓글 id
            "secret": false,
            "content": "ㅎㅎ",
            "replies": [],
            "feelings": []
        },
        {
            "userInfo": {
                "id": 9021279491,
                "name": "이왜진123",
                "image": ""
            },
            "id": 8846402458, // 댓글 id
            "secret": false,
            "content": "ㅎ호호",
            "replies": [],
            "feelings": []
        },
        {
            "userInfo": {
                "id": 9021279491,
                "name": "이왜진123",
                "image": ""
            },
            "id": 5409327627, // 댓글 id
            "secret": false,
            "content": "ㅁㄴㅇㄹ",
            "replies": [],
            "feelings": []
        }
    ]
}
```

delete관련 에러
<img width="1373" alt="스크린샷 2022-10-09 오후 9 30 46" src="https://user-images.githubusercontent.com/71386219/194756935-0d0e8057-cb1b-43b1-8456-e49349afc2db.png">

## 3. 댓글 조회 생성 시간 관련 데이터 추가 요청

댓글 조회 요청 시 댓글 생성 시간 관련 데이터가 없습니다. 우선 최초 생성 시간 데이터로 하고 추후에 최종 수정 시간으로 할지, 최초 생성 시간으로 할지 정하면 좋을 것 같습니다. @hoeun0723

**Comment by philos1234** [comment]
1번에서 댓글 작성자를 넣어주는  "userName"  부분은 필요가 없어서 없애도 될 거 같은데 어떤가요?
이미 토큰 안에 작성자의 정보가 있어 괜찮을 것 같아요

**Comment by kimyouknow** [comment]
> 1번에서 댓글 작성자를 넣어주는 "userName" 부분은 필요가 없어서 없애도 될 거 같은데 어떤가요?
> 이미 토큰 안에 작성자의 정보가 있어 괜찮을 것 같아요
> @kimyouknow

좋습니다~ 작성자 관련 정보는 token에 들어있으니 빼도 되겠네요👍
