### ISSUE TITLE
기술스택 양식 정하면 좋을 것 같아요 댓글로 의견 달아주세요🤔

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#21]
# 기술스택 양식 정하기

회원가입 구현하다가 생각났습니다. 기술스택을 양식으로 제출할 때, javascript, java 와 같이 문자로 보내기보다는 key,value로 정해두고 key값만 보내는 건 어떨까요? 

회원가입 서비스 뿐만 아니라 다른 서비스에서 기술스택을 사용하게 될 때도 아래처럼 key 값으로 접근하는게 안전할 것 같다는 생각을 했습니다. 

## 예시

```
    { id: 0, value: 'javascript' },
    { id: 1, value: 'java' },
    { id: 2, value: 'typescript' },
    { id: 3, value: 'python' },
    { id: 4, value: 'react' },
    { id: 5, value: 'spring' },
    { id: 6, value: 'xd' },
```

**Comment by philos1234** [comment]
나쁘지는 않으나, 이렇게되면 커스텀으로 추가하는 기술스택에 대한 정보는 알 수 없게 됩니다.
즉 우리가 정해놓지 않은 기술스택은 추가할 수 없게되는데, 혹시 해결방법이 있을까요
