### ISSUE TITLE
POST user/join 관련 요청 사항

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#22]
### 요청사항
1. 노션 api 설계 부분에서 `POST  /user/signup`(swagger에는 join으로 되어 있음)과 `POST /user/myprofile` 부분 수정이 필요해보여요. 
2. inputValidation도 알려주세요. 

@philos1234

**Comment by philos1234** [comment]
1번은 어떤 부분을 수정해야 합니까?

**Comment by kimyouknow** [comment]
POST profile할 때 보내는 정보가 이제 join으로 합쳐진거 아닌가요?
