### ISSUE TITLE
[BE]  GET api/team & GET api/user 수정 요청

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#248]
### 1. GET api/team 요청시 image 및 기술스택 배열, 희망 작업 기간

- 작성자의 이미지 정보는 있지만 팀 생성시 등록한 `이미지`가 response로 오지 않습니다. 추가 요청합니다. 
- 팀 생성시 등록한 `기술스택` 배열이 오지 않습니다. 추가 요청합니다. 
- - 팀 생성시 등록한 `희망 작업 기간` 정보가 오지 않습니다. 추가 요청합니다. 

### 2. GET api/team & GET api/user 요청시 기술스택 response항목 수정

아래와 같이 `기술명배열`이 옵니다. 

<img width="221" alt="스크린샷 2022-12-31 오후 9 27 50" src="https://user-images.githubusercontent.com/71386219/210136753-fc055c57-dbf8-4dc0-8c09-1f92f9bd745b.png">

기대 동작

아래와 같은 `기술 DTO` 배열

<img width="330" alt="스크린샷 2022-12-31 오후 9 28 18" src="https://user-images.githubusercontent.com/71386219/210136764-748c8868-6527-4008-b4fa-4448b089e34e.png">

**Comment by philos1234** [comment]
제대로 오는게 없네?

**Comment by philos1234** [comment]
근데 URL을 직접적으로 써주시면 좋겠습네다

**Comment by kimyouknow** [comment]
GET api/team & GET api/user 이게 풀주소 아닌가요?

**Comment by philos1234** [comment]
맞습니다 미안합니다
