### ISSUE TITLE
이미지 서버에 이미지가 올라갔지만 요청을 보내지 않았을 때 해결하기

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#35]
# 현재 이미지 업로드를 구현할 수 있는 2가지 방법

## 1. 프론트에서 s3로 직접 이미지 업로드
- 이미지가 성공적으로 업로드되면 s3에 해당 이미지가 저장된 경로를 받음
- 해당 경로(또는 경로 엔트리 포인트인 파일 이름)을 form 제출할 때 이미지 데이터로 함께 제출

### 1.1 프론트 구현사항: 
- 관련 파일: components/ImageUploader/index.jsx
- 관련 정보: aws-sdk(library), aws-s3

### 1.2 기타
- s3 키같은 환경변수 정보들을 .env에 저장해둠. (.gitignore에 올리지 않음)

## 2. 프론트에서 `/upload`경로로 was(우리 서버)에 이미지 업로드 요청
- 이미지가 성공적으로 업로드되면 s3에 해당 이미지가 저장된 경로를 받음
- 해당 경로(또는 경로 엔트리 포인트인 파일 이름)을 프론트에 response로 전달
- 해당 경로(또는 경로 엔트리 포인트인 파일 이름)을 form 제출할 때 이미지 데이터로 함께 제출

### 2.1 프론트 구현사항: 
- 관련 파일: src/hooks/useFileUploader.js
- 관련 정보: javascript FormData, response type('content-type': 'multipart/form-data',)

# 추가적으로 필요한 사항

## 1. 이미지 서버 삭제 요청

위의 두 가지 경우 중 어떤 경우라도 다음과 같은 상황에서 문제가 발생
```
1. 사용자가 이미지 서버에 이미지 업로드 요청
2. 이미지 서버에 이미지가 성공적으로 업로드
3. 사용자가 브라우저에서 벗어남(페이지 이동, 브라우저 종료 등등,,)
4. 이미지 서버에는 이미지가 올라갔지만, was(우리 서버)로 요청을 따로 보내지 않아 낭비되는 상황
```

### 1.1 해결책

아직 구현해보지는 않았지만 다음과 같은 해결책이 있다.

- 3번 상황일 때 s3에 해당 이미지 삭제 요청을 보내기

Ref: #25

**Comment by philos1234** [comment]
1.1 해결책대로 하면 3번 상황 해결가능할것 같고
4번에 대한 문제상황이 잘 이해가 되지 않아서.. s3에 있는 이미지를 우리가 요청하지 않는 상황을 말하는 건가요?
