### ISSUE TITLE
팀 댓글 서비스 관련 수정 필요

### ISSUE THREAD

**Issue by hyojeongyun** [yulpumta-clone-team/Co-nect#37]
## 요약
유저/팀 댓글 API 관련 수정해야 할 부분이 있을 것 같습니다.

* 유저/팀 댓글 dto의 feelings에 UserDto가 아닌 User의 ID만 보이도록 수정
* 댓글 좋아요 등록 API의 HTTP method를 PATCH로 수정

**Comment by philos1234** [comment]
유저 댓글 부분은 모두 수정했습니다
