### ISSUE TITLE
회원가입 Page + Main modal창

### ISSUE THREAD

**Issue by hoeun0723** [yulpumta-clone-team/Co-nect#38]
## 제목
회원가입 Page

## 요약 (개요) 
회원가입 입력 정보 관련 부분 페이지 생성하기.
(상세내용 관련 입력 부분--> main화면에 있는 openmodal 버튼 방식을 참고하여 모달로)
+모달 창 닫기 버튼 오류 난 부분 수정하기.

## 추가 사항
notion 프론트 - 회원가입 페이지에 회의 사항 내용 정리해두었음.

**Comment by kimyouknow** [comment]
> 추후 작성 된 issue #81 을 참고하여 확인 하도록. (모달창의 코딩 단계를 좀 더 세분화 하여 나눴다. Notion 또한 참고 필요)

아 이미 여기선 참고링크 해주셨네요 ...ㅎㅎㅎ좋습니다!
