### ISSUE TITLE
노션 API 설계 업데이트 요청

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#46]
# 요청사항

1. 노션 API 설계 페이지 업데이트 부탁드립니다. 

swagger에 나와있는 api는 `브랜치를 합치기 전에 최신화가 되지 않은 문제`가 있는 것 같습니다. 서버 브랜치를 develop으로 최신화하더라도 api설계는 따로 정리해야 프론트도 동시에 작업이 가능하고, api 연결할 때 에러를 줄일 수 있을 것 같습니다. 

2. api 변수명 통일 

#41 이슈에 남긴 것 외에도 유저와 팀 관련 api에서 변수명이 조금씩 다른 부분이 있습니다. 일관성을 위해 같은 기능이거나, 같은 데이터이면 통일하는 건 어떨까요?

**Comment by hyojeongyun** [comment]
1. 팀 게시물과 팀 댓글 API들은 노션에 업데이트했습니다.
2. 유저와 팀 변수명 통일했습니다.
