### ISSUE TITLE
api 수정에 따른 질문 및 수정요청

### ISSUE THREAD

**Issue by kimyouknow** [yulpumta-clone-team/Co-nect#53]
api 수정에 따른 질문 및 수정요청

## 1. GET - showUserList

- slogan: boolean 맞나요? string 같은데..
- skills: [string, string2] -> [number, number2] 로 수정요청. [기술스택양식이슈 #29](https://github.com/yulpumta-clone-team/Co-nect/issues/29)

## 2. GET- 내가 좋아요한 유저 리스트 불러오기

- 좋아요 누른 유저 목록만 불러오는게 맞나요? (유저가 좋아요를 누를 수 있는 게시글은 유저 프로필 + 팀 게시글 두 개가 있어요!)

## 3. GET-showTeamList, GET - showUserList

- 팀 게시글에는 read라는 조회수가 있는데 유저 게시글에는 조회수 관련 데이터가 없네요. 의도한 부분일까요?
- status(boolean): 어떤 상태를 말하는 걸까요?
  - GET-마이페이지에서는 (true -> 인력시장에서 사라짐, false -> 인력시장에서 보임) 이렇게 정리되어 있는데 이 내용이 맞다면 다음과 같은 문제가 있다고 생각해요!
    - 1. 서버에서 false값만 주면 프론트에서 계산하지 않아도 돼서 렌더링이 빨라짐
    - 2. teamList에서 status의 의미가 모호함.

**Comment by philos1234** [comment]
1번 내용은 해당 내용대로 수정했습니다
2번은 좋아요 누른 유저 목록만 불러오는게 맞습니다 
팀 좋아요 게시물 불러오는 API 따로 만들어줘야합니다 @hyojeongyun 
3번 원래 조회수는 설계하지 않았던걸로 아는데.. 있었나요? 
현재 코드 보면 팀 서비스에도 조회수 관련한 로직이 없는데, DTO에만 있는거 같아서 확인좀 부탁합니다 @hyojeongyun 

status는 서버쪽에서 해당 엔티티의 상태관리를 위한 속성입니다. 서버에서 false값만 주면 렌더링이 빨라진다는게 무슨말인지??
