### ISSUE TITLE
읽은 목록과 좋아요한 목록 관련 질문

### ISSUE THREAD

**Issue by hyojeongyun** [yulpumta-clone-team/Co-nect#61]
## 요약 (개요) 
게시글 읽은 목록과 좋아요한 목록 API가
* 유저 게시글 히스토리 API / 팀 게시글 히스토리 API
* 유저 게시글 좋아요한 목록 API / 팀 게시글 좋아요한 목록 API

이렇게 유저와 팀이 분리되어 있는 건가요??

## 참고 사항
* [노션](https://www.notion.so/ea00034b565a413c81f25be10f770f3c)

**Comment by kimyouknow** [comment]
`노션 메인/내 관심글`에 회의 내용을 정리했습니다.
