### ISSUE TITLE
로그인 메인 화면 모달창 이어서 코딩

### ISSUE THREAD

**Issue by hoeun0723** [yulpumta-clone-team/Co-nect#70]
## 모달창 제작.(로그인 관련)
로그인 부분 모달창 제작

## 로그인과 메인화면 모달창 제작하기.
* 로그인화면 모달창으로 띄우기. 메인화면에 있는 모달창 포함하여 수정하기.

## 주의사항
일단 메인 화면 모달창보단, 로그인 부터 제작예정.

**Comment by hoeun0723** [comment]
추가 issue 확인 필요함. 일단 닫는 기능 구현 완료.

**Comment by kimyouknow** [comment]
> 추가 issue 확인 필요함. 일단 닫는 기능 구현 완료.

https://github.com/yulpumta-clone-team/Co-nect/issues/81#issue-1303492435 관련 이슈 링크만 추가했어요!
